on: [push]

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  scan_project_job:
    runs-on: ubuntu-latest
    name: TEST
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - name: Scanproject Action live!
        uses: ./
        id: scanproject
      - name: Get the output time
        run: echo "The time was ${{ steps.scanproject.outputs.report }}"
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk-code.sarif
