on:
  - push
  - workflow_dispatch

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  scan_project_job:
    runs-on: ubuntu-latest
    name: TEST
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - name: Scanproject Action live!
        uses: ./
        id: scanproject
      - name: test summary
        run: echo '### Hello world! 🚀' >> $GITHUB_STEP_SUMMARY
      - name: Store report for debugging
        uses: actions/upload-artifact@v3
        with:
          name: tsp-report
          path: tsp-report.sarif
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: tsp-report.sarif
      - name: env
        run: env | grep GITHUB
